### ISSUE TITLE
What's the point of having a private field and a public property with default set and get

### ISSUE THREAD

**Issue by Walter-Sparrow** [Sparckmen/C-Sharp-Lab_2-Model#1]
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/3d8dd44893ff7f0c153433fd8c22e25d01363cec/Lab_2(Model)/Model/Person.cs#L9-L13

**Comment by Sparckmen** [comment]
1ea25ff983628cc2f4d2b10465e9d9567e9dec57

**Comment by Walter-Sparrow** [comment]
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/70440138a61ef8162869d802fb278f6ec382406d/Lab_2(Model)/Model/Person.cs#L9
Keep code consistent, your public field is now in lower case
