### ISSUE TITLE
Missing an access modifier

### ISSUE THREAD

**Issue by Walter-Sparrow** [Sparckmen/C-Sharp-Lab_2-Model#10]
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/70440138a61ef8162869d802fb278f6ec382406d/Lab_2(Model)/Controller/SimulationController.cs#L17

**Comment by Sparckmen** [comment]
Enjoy
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/71d4e8dcb4406791be40fabdc8c87aa01f2ee8bc/Lab_2(Model)/Controller/SimulationController.cs#L14
