### ISSUE TITLE
Avoid magic numbers

### ISSUE THREAD

**Issue by Walter-Sparrow** [Sparckmen/C-Sharp-Lab_2-Model#11]
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/70440138a61ef8162869d802fb278f6ec382406d/Lab_2(Model)/Model/Discs.cs#L18-L28
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/70440138a61ef8162869d802fb278f6ec382406d/Lab_2(Model)/Model/Discs.cs#L21
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/70440138a61ef8162869d802fb278f6ec382406d/Lab_2(Model)/Model/Discs.cs#L23
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/70440138a61ef8162869d802fb278f6ec382406d/Lab_2(Model)/Model/Discs.cs#L26

**Comment by Sparckmen** [comment]
У меня фильмы хранятся в определенном формате, и как сделать по-другому я хз

**Comment by Sparckmen** [comment]
I hope you are happy now
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/71d4e8dcb4406791be40fabdc8c87aa01f2ee8bc/Lab_2(Model)/Model/Discs.cs#L18-L31

**Comment by Walter-Sparrow** [comment]
I would suggest defining new variable (Convert.ToInt32(data[lengthId].Split(' ')[lengthId]))
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/71d4e8dcb4406791be40fabdc8c87aa01f2ee8bc/Lab_2(Model)/Model/Discs.cs#L29
