### ISSUE TITLE
Unused variable and missed access modifier

### ISSUE THREAD

**Issue by Walter-Sparrow** [Sparckmen/C-Sharp-Lab_2-Model#13]
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/71d4e8dcb4406791be40fabdc8c87aa01f2ee8bc/Lab_2(Model)/Model/Person.cs#L14

**Comment by Sparckmen** [comment]
It's gone
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/a862e904235e417d6652619286b33cd0b0066397/Lab_2(Model)/Model/Person.cs#L8-L18
