### ISSUE TITLE
Array already has an Enumerator

### ISSUE THREAD

**Issue by Walter-Sparrow** [Sparckmen/C-Sharp-Lab_2-Model#14]
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/71d4e8dcb4406791be40fabdc8c87aa01f2ee8bc/Lab_2(Model)/Model/Friends.cs#L39-L42
Documentation:
https://docs.microsoft.com/en-us/dotnet/api/system.array.getenumerator?view=net-5.0

**Comment by Sparckmen** [comment]
This doesn't wok in my case it's only for generic
```System.Collections.IEnumerator myEnumerator = myArr.GetEnumerator();
      Console.WriteLine( "The Array contains the following values:" );
      while (( myEnumerator.MoveNext() ) && ( myEnumerator.Current != null ))
         Console.WriteLine( "[{0}] {1}", i++, myEnumerator.Current );

**Comment by Walter-Sparrow** [comment]
Idk what are you talking about, you can literally return `friends.GetEnumerator()`

**Comment by Sparckmen** [comment]
Here you are
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/a862e904235e417d6652619286b33cd0b0066397/Lab_2(Model)/Model/Friends.cs#L38-L41
