### ISSUE TITLE
Don't generate data into non-existence, use Enum.Parse or wrap this line in an if-statement and think about errors in the file

### ISSUE THREAD

**Issue by Walter-Sparrow** [Sparckmen/C-Sharp-Lab_2-Model#15]
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/e1d1868c4a26c837c8b11de25d8d1d4b909765fc/Lab_2(Model)/Model/Discs.cs#L24
Documentation:
https://docs.microsoft.com/en-us/dotnet/api/system.enum.parse?view=net-5.0

**Comment by Sparckmen** [comment]
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/86a17a362add23fa31060b8346097658ac2e3df4/Lab_2(Model)/Model/Discs.cs#L24-L25
