### ISSUE TITLE
You can use the find method from List<T>

### ISSUE THREAD

**Issue by Walter-Sparrow** [Sparckmen/C-Sharp-Lab_2-Model#3]
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/3d8dd44893ff7f0c153433fd8c22e25d01363cec/Lab_2(Model)/Model/Person.cs#L34-L41
Documentation:
https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.find?view=net-5.0

**Comment by Sparckmen** [comment]
1ea25ff983628cc2f4d2b10465e9d9567e9dec57
