### ISSUE TITLE
The private "film" field is unnecessary, you can type { get; } inside the property and the compiler will do the same for you

### ISSUE THREAD

**Issue by Walter-Sparrow** [Sparckmen/C-Sharp-Lab_2-Model#4]
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/3d8dd44893ff7f0c153433fd8c22e25d01363cec/Lab_2(Model)/Model/IDisc.cs#L18-L25

**Comment by Sparckmen** [comment]
1ea25ff983628cc2f4d2b10465e9d9567e9dec57
