### ISSUE TITLE
Perhaps you mean calling the Count property, because List<T> doesn't have a Count method

### ISSUE THREAD

**Issue by Walter-Sparrow** [Sparckmen/C-Sharp-Lab_2-Model#6]
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/3d8dd44893ff7f0c153433fd8c22e25d01363cec/Lab_2(Model)/Model/Discs.cs#L53

**Comment by Sparckmen** [comment]
1ea25ff983628cc2f4d2b10465e9d9567e9dec57

**Comment by Walter-Sparrow** [comment]
Gave you a comment in the commit
