### ISSUE TITLE
The Person class says otherwise

### ISSUE THREAD

**Issue by Walter-Sparrow** [Sparckmen/C-Sharp-Lab_2-Model#7]
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/3d8dd44893ff7f0c153433fd8c22e25d01363cec/Lab_2(Model)/Model/DiscFactory.cs#L9
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/44072fcc3dae462d8a6a5baf22f33ad4a3216144/Lab_2(Model)/Model/Person.cs#L26

**Comment by Sparckmen** [comment]
Я забыл коммент исправить, изначально думал по-другому сделать
