### ISSUE TITLE
I think HashSet is more suitable for this task

### ISSUE THREAD

**Issue by Walter-Sparrow** [Sparckmen/C-Sharp-Lab_2-Model#8]
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/44072fcc3dae462d8a6a5baf22f33ad4a3216144/Lab_2(Model)/Model/Friends.cs#L27-L29

**Comment by Sparckmen** [comment]
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/13e16fea04c3cd58db225f32bd9633f1c03a82dc/Lab_2(Model)/Model/Friends.cs#L17-L30
