### ISSUE TITLE
I think this is unnecessary because you call this method from a non-main tread

### ISSUE THREAD

**Issue by Walter-Sparrow** [Sparckmen/C-Sharp-Lab_2-Model#9]
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/44072fcc3dae462d8a6a5baf22f33ad4a3216144/Lab_2(Model)/SimulationView.cs#L40
Documentation: 
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.invokerequired?view=net-5.0

**Comment by Walter-Sparrow** [comment]
Or separate the logic into a new method and only then wrap it in InvokeRequired

**Comment by Sparckmen** [comment]
Как мне Ира скинула, она везде заворачивала этим if (InvokeRequired) в каждом методе, вызываемом на форме

**Comment by Walter-Sparrow** [comment]
I gave you a suggestion in the comment above

**Comment by Sparckmen** [comment]
Сейчас метод настолько маленький, что не вижу смысла оборачивать его
https://github.com/Sparckmen/C-Sharp-Lab_2-Model/blob/71d4e8dcb4406791be40fabdc8c87aa01f2ee8bc/Lab_2(Model)/SimulationView.cs#L34-L43

**Comment by Walter-Sparrow** [comment]
Have you changed your mind about doing the animation?

**Comment by Sparckmen** [comment]
Нет, я просто отдельно буду вызывать этот метод из контроллера посекундно, чтобы обновлялось движение всех одновременно
```
            Point start = person.Location;
            Point end = new Point(toPerson.Location.X - 60, toPerson.Location.Y);
            int steps = Convert.ToInt32(start.GetDistanceTo(end) / personSpeed);
            for (int step = 0; step < steps; step++)
            {
                _simulationView.UpdatePosition(person, new Point(start.X + (end.X - start.X) * step / steps, start.Y + (end.Y - start.Y) * step / steps));
                Thread.Sleep(5);
            }

**Comment by Walter-Sparrow** [comment]
We'll see this in the code
